name: test
 2 on: push
 3 jobs:
 4 　test:
 5     runs-on: ubuntu-22.04
 6     container: Nutarou3/ubuntu22.04-ros2:latest #前ページのコンテナを使うという宣言
 7     steps:
 8       - uses: actions/checkout@v2 #コンテナのカレントディレクトリにリポジトリを配置
 9       - name: build and test
10         run: |
11           rsync -av ./ /root/ros2_ws/src/mypkg/    # リポジトリの下をros2_ws下にコピー
12           cd /root/ros2_ws　#↓追加のパッケージが必要なら実行前にrosdep
13           bash -xv ./src/mypkg/test/test.bash /root #実行
